### ISSUE TITLE
The documentation link is down

### ISSUE THREAD

**Issue by dmsherazi** [Sufi-Al-Hussaini/libdo#1]
The blog hosting the documentation is down or the domain has changed. It would be great to either update the links or add the documentation to this repo.

**Comment by hu55a1n1** [comment]
Thank you for opening this issue! I will update the links. Here's the doc page -> https://github.com/hu55a1n1/hu55a1n1.github.io/blob/master/_posts/2018-04-11-predicate-driven-programming.markdown
